In [1]:
# Imports
from random import random
import numpy as np
import torch
import polars as pl


In [2]:
# Comments
# This is a comment

"""
This is a docstring.
As such, we can use this for many things, including multiple lines.
As such.
"""

'\nThis is a docstring.\nAs such, we can use this for many things, including multiple lines.\nAs such.\n'

In [3]:
def my_function():
    """Here is a docstring inside a function, for example."""
    pass

print(my_function.__doc__)


Here is a docstring inside a function, for example.


In [4]:
# Variables
a = 50  # integer
b = 1.39  # float
ticker = "BTC"  # string
is_profit = True  # boolean


In [5]:
# Operators and Expressions
c = a + b
print(c)

c = a - b
print(c)

c = a * b
print(c)

c = a / b
print(c)

c = a % b
print(c)

51.39
48.61
69.5
35.97122302158274
1.3500000000000034


In [6]:
# Lists and Arrays
prices_list = [2.34, 1.21, 7.98, 3.98, "BTC"]
print(prices_list)

prices_array = np.array([2.34, 1.21, 7.98, 3.98])
print(prices_array)

prices_tensor = torch.tensor(prices_array)
print(prices_tensor)

[2.34, 1.21, 7.98, 3.98, 'BTC']
[2.34 1.21 7.98 3.98]
tensor([2.3400, 1.2100, 7.9800, 3.9800], dtype=torch.float64)


In [7]:
# Appending to list
prices_list.append(5.92)
print(prices_list)


[2.34, 1.21, 7.98, 3.98, 'BTC', 5.92]


In [9]:
# Accessing list elements
first_item = prices_list[0]
last_item = prices_list[-1]
first_two_items = prices_list[:2]
all_but_last = prices_list[:-1]
print("First item:", first_item)
print("Last item:", last_item)
print("First two items:", first_two_items)
print("All but last:", all_but_last)


First item: 2.34
Last item: 5.92
First two items: [2.34, 1.21]
All but last: [2.34, 1.21, 7.98, 3.98, 'BTC']


In [10]:
# Length of list, array, and tensor
list_length = len(prices_list)
array_length = len(prices_array)
tensor_length = len(prices_tensor)

print(f"List length: {list_length}")
print(f"Array length: {array_length}")
print(f"Tensor length: {tensor_length}")

List length: 6
Array length: 4
Tensor length: 4


In [12]:
# Shapes and reshaping
open_prices = [2.34, 1.2, 1.19, 2.31]
close_prices = [2.37, 2.0, 1.17, 2.22]

prices_array = np.array([open_prices, close_prices])
print(prices_array)
print(f"Shape: {prices_array.shape}")

reshaped = prices_array.reshape(4, 2)
print(reshaped)

flattened = prices_array.reshape(1, 8)[0]
print(flattened)

[[2.34 1.2  1.19 2.31]
 [2.37 2.   1.17 2.22]]
Shape: (2, 4)
[[2.34 1.2 ]
 [1.19 2.31]
 [2.37 2.  ]
 [1.17 2.22]]
[2.34 1.2  1.19 2.31 2.37 2.   1.17 2.22]


In [13]:
""" This code covers the main concepts discussed in the lecture, including:

Importing libraries
Comments and docstrings
Variables (integers, floats, strings, booleans)
Basic operators and expressions
Lists, arrays, and tensors
List operations (appending, accessing elements)
Getting lengths of lists, arrays, and tensors
Array shapes and reshaping

Note that Polars wasn't directly used in this part of the lecture, 
but it's imported as pl for potential future use. The code uses NumPy arrays and PyTorch tensors
as discussed in the lecture.
"""

" This code covers the main concepts discussed in the lecture, including:\n\nImporting libraries\nComments and docstrings\nVariables (integers, floats, strings, booleans)\nBasic operators and expressions\nLists, arrays, and tensors\nList operations (appending, accessing elements)\nGetting lengths of lists, arrays, and tensors\nArray shapes and reshaping\n\nNote that Polars wasn't directly used in this part of the lecture, \nbut it's imported as pl for potential future use. The code uses NumPy arrays and PyTorch tensors\nas discussed in the lecture.\n"